---
title: "MATH214-Final-Project"
author: 
- Ahmed A. Radhi - 100049714
- Khalid Talal Suliman - 100053835
date: "5/7/2021"
output: html_document
---

```{r}
# Loading Libraries 

library(tidyverse)
library(magrittr)
library(modelr)
library(nycflights13)
library(lubridate)
library(splines)
library(forcats)
```

# Introduction and Description

The data describes road accidents across Leeds in the year 2017 provided by `data.gov.uk`. It includes location, date, time, road settings and casualty information for each accident that transpired during the year. 

**Reference :** https://data.world/datagov-uk/6efe5505-941f-45bf-b576-4c1e09b579a1


# Data Parsing and Import

```{r}
# Loading & Parsing Data

Accidents_2017 <- read_csv("Data/datagov-uk-6efe5505-941f-45bf-b576-4c1e09b579a1/2017-8.csv", 
                           col_names = c("Reference_Number","Easting","Northing","Vehicles_Num","Accident_Date","Time","Road_Class","Road_Surface",
                                         "Lightning_Cond","Weather_Cond","Vehicle_Type","Casualty_Class","Severity","Gender","Age"), skip = 1)


Accidents_Date <- Accidents_2017$Accident_Date
Accidents_Date <- parse_date(Accidents_Date, "%m/%d/%Y")

Time <- Accidents_2017$Time
Time <- parse_time(Time, "%H%M")

Accidents_2017 <- Accidents_2017 %>%
  select(1:4, 7:15) %>%
  mutate(Accidents_Date, Time) 

Accidents_2017 <- Accidents_2017[,c(1:4,14,15,5:13)]

# Correcting spelling mistakes

Lightning_Cond <- 
  str_replace(Accidents_2017$Lightning_Cond,"Darkness: Street lights present and lit and lit","Darkness: Street lights present and lit")


Road_Class <- str_replace_all(Accidents_2017$Road_Class,
      c("A.*" = "A","B.*" = "B","M.*" = "M"))


Road_Surface <- str_replace(Accidents_2017$Road_Surface,"^F.*","Snow")


Weather_Cond <- word(Accidents_2017$Weather_Cond,1) 
Weather_Cond <- str_replace(Weather_Cond,"Fog","Other")


Vehicle_Type <- word(Accidents_2017$Vehicle_Type,1)
Vehicle_Type <- str_replace_all(Vehicle_Type,
      c(".Private" = "Taxi",
        "Ca.*" = "Car","Pedal" = "Cycle"))
Vehicle_Type <- str_replace(Vehicle_Type,"TaxiTaxi", "Taxi")


# Adding the improved columns to the dataset 

Accidents_2017 <- Accidents_2017 %>% 
  select(1:6,12:15) %>%
  mutate(Lightning_Cond,Weather_Cond,Road_Class,Road_Surface,Vehicle_Type,
         Year = year(Accidents_Date),
         Month = month(Accidents_Date),
         Day = day(Accidents_Date),
         Hour = hour(Time),
         Minute = minute(Time),
         Accidents_DateTime = make_datetime(Year, Month, Day, Hour, Minute))

Accidents_2017 <- Accidents_2017[,c(1:4, 16:20, 5:6, 21, 7:15)]

# Assigning the columns to their proper classes. 

for(i in 2:length(Accidents_2017)) {
    if(is.character(Accidents_2017[[i]])) {
        Accidents_2017[[i]] <- as.factor(Accidents_2017[[i]])
    } else if (is.numeric(Accidents_2017[[i]])) {
        Accidents_2017[[i]] <- as.numeric(Accidents_2017[[i]])
    }
}

Accidents_2017

# Checking NAs 

sum(rowSums(is.na(Accidents_2017)))

# No NA values to explore
```

```{r}
(Accidents_Hour <- Accidents_2017 %>% count(Hour))

(DoW_Hour <- Accidents_2017 %>% 
  mutate(day_of_week = wday(Accidents_Date, label = TRUE))%>%
  count(day_of_week, Hour))

ggplot(Accidents_Hour, mapping = aes(Hour, n)) +
  geom_line() +
  geom_point()

ggplot(DoW_Hour, mapping = aes(Hour, n, color = day_of_week))+
  geom_line()+
  geom_point()

ggplot(Accidents_Hour, mapping = aes(Hour,n))+
  geom_line()+
  geom_point()+
  geom_line(data = DoW_Hour, mapping = aes(Hour,n,color = day_of_week))
```

```{r}
# Distribution of Accidents across the course of the day for every day of the year

Accidents_2017 %>%
  mutate(Accidents_by_Hour = update(Accidents_DateTime, yday = 1)) %>%
  ggplot(mapping = aes(Accidents_by_Hour)) +
  geom_freqpoly(binwidth = 3600) # 5 mins interval 

# Distribution of Accidents across the course of the day for every day (and month) of the year

Accidents_2017 %>%
  mutate(Accidents_by_Hour = update(Accidents_DateTime, yday = 1),
         Accidents_by_Month = factor(Month)) %>%
  ggplot(mapping = aes(Accidents_by_Hour, color = Accidents_by_Month)) +
  geom_freqpoly(binwidth = 3600) # 1 hour interval

# Distribution of Accidents across the course of the day for every day (and month) of the year w/ y-axis as density

Accidents_2017 %>%
  mutate(Accidents_by_Hour = update(Accidents_DateTime, yday = 1),
         Accidents_by_Month = factor(Month)) %>%
  ggplot(mapping = aes(Accidents_by_Hour, color = Accidents_by_Month)) +
  geom_freqpoly(mapping = aes(y = ..density..), binwidth = 3600) # 1 hour interval

```


```{r}
daily <- Accidents_2017 %>%
  group_by(Accidents_Date) %>%
  summarise(n = n()) %>%
  mutate(wday = wday(Accidents_Date, label = T, abbr = F))

daily

# Number of flights per day

ggplot(daily, mapping = aes(Accidents_Date, n)) +
  geom_line()

# Number of flights in each day of the week
ggplot(daily, mapping = aes(wday, n)) + 
  geom_boxplot()
  
ggplot(daily, mapping = aes(wday, n)) + 
  geom_bar(stat = "identity")

# Fitting a linear model w/ predictions & residuals

model1 <- lm(n ~ wday, data = daily)
grid <- daily %>%
  data_grid(wday) %>%
  add_predictions(model1, "n")
ggplot(daily, mapping = aes(wday, n))+
  geom_boxplot() +
  geom_point(data = grid, colour = "red", size = 4)
daily <- daily %>%
  add_residuals(model1)
ggplot(data = daily, mapping = aes(Accidents_Date, resid)) +
  geom_ref_line(h = 0) +
  geom_line()

```

